
- hosts: dev-worker
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
    - name: Start Docker Service
      service:
        name: docker
        state: started
